#!/usr/bin/env bash

D14K_PROFILE_LABEL="${D14K_PROFILE_LABEL:-Filler production}"
D14K_REMOTE_SSH_ALIAS="${D14K_REMOTE_SSH_ALIAS:-filler-hostinger}"
D14K_REMOTE_SITE_URL="${D14K_REMOTE_SITE_URL:-https://filler.com.ua}"
D14K_REMOTE_WP_PATH="${D14K_REMOTE_WP_PATH:-/home/u782807436/domains/filler.com.ua/public_html}"
D14K_REMOTE_PLUGIN_PATH="${D14K_REMOTE_PLUGIN_PATH:-/home/u782807436/domains/filler.com.ua/public_html/wp-content/plugins/d14k-merchant-feed/}"
D14K_REMOTE_FEED_URL="${D14K_REMOTE_FEED_URL:-https://filler.com.ua/marketplace-feed/horoshop/}"
D14K_MARKETPLACE_FEED_URL="${D14K_MARKETPLACE_FEED_URL:-https://filler.com.ua/marketplace-feed/horoshop/}"
D14K_MARKETPLACE_FEED_FORMAT="${D14K_MARKETPLACE_FEED_FORMAT:-csv}"
D14K_PLUGIN_SLUG="${D14K_PLUGIN_SLUG:-d14k-merchant-feed}"
D14K_WP_CLI_ARGS="${D14K_WP_CLI_ARGS:---skip-plugins=salesdrive}"
D14K_SMOKE_KIND="${D14K_SMOKE_KIND:-marketplace_feed}"
D14K_RUN_HTTP_CHECKS_DEFAULT="${D14K_RUN_HTTP_CHECKS_DEFAULT:-1}"
D14K_DEPLOY_REQUIRE_CONFIRM="${D14K_DEPLOY_REQUIRE_CONFIRM:-1}"
D14K_DEPLOY_CONFIRM_VAR="${D14K_DEPLOY_CONFIRM_VAR:-D14K_DEPLOY_PRODUCTION_CONFIRM}"
D14K_DEPLOY_CONFIRM_VALUE="${D14K_DEPLOY_CONFIRM_VALUE:-DEPLOY}"
D14K_CACHE_FLUSH_COMMAND="${D14K_CACHE_FLUSH_COMMAND:-wp --path='/home/u782807436/domains/filler.com.ua/public_html' --skip-plugins=salesdrive cache flush}"
D14K_POST_DEPLOY_COMMAND="${D14K_POST_DEPLOY_COMMAND:-curl -s -X POST 'https://api.cloudflare.com/client/v4/zones/44d2bc486baf0d5a3789482d80b5a963/purge_cache' -H \"Authorization: Bearer \$(security find-generic-password -w -s 'codex/gmc-feed/filler-cloudflare-token')\" -H 'Content-Type: application/json' --data '{\"purge_everything\":true}'}"
