<?php
if (!defined('ABSPATH')) {
    exit;
}

/**
 * WooCommerce → Prom.ua Product Exporter
 *
 * Two export strategies:
 *
 * 1. BATCH SYNC (recommended for large catalogs):
 *    Triggers POST /products/import_url on Prom.ua with the URL
 *    of the existing YML feed already generated by D14K_YML_Generator.
 *    Prom fetches and processes the XML on its own servers.
 *
 * 2. DIRECT SYNC:
 *    Pushes individual product changes (price, stock, status) directly
 *    via POST /products/edit_by_external_id — useful for real-time hooks
 *    when a single WooCommerce product is saved.
 *
 * @since 4.0.0
 */
class D14K_Prom_Exporter
{
    /** @var D14K_Prom_API */
    private $api;

    /** @var D14K_YML_Generator|null */
    private $yml_generator;

    public function __construct($api, $yml_generator = null)
    {
        $this->api           = $api;
        $this->yml_generator = $yml_generator;

        // Hook: when a WooCommerce product is saved, optionally sync to Prom
        add_action('woocommerce_update_product', array($this, 'on_product_save'), 10, 1);
    }

    // -------------------------------------------------------------------------
    // Strategy 1: Batch export via import_url
    // -------------------------------------------------------------------------

    /**
     * Regenerate the Prom YML feed and tell Prom.ua to fetch it.
     *
     * @return array  ['success' => bool, 'import_id' => int|null, 'message' => string]
     */
    public function push_feed_to_prom()
    {
        if (!$this->api->has_token()) {
            return array('success' => false, 'message' => 'API-токен Prom.ua не налаштований', 'import_id' => null);
        }

        // 1. Regenerate the YML feed if generator available
        if ($this->yml_generator) {
            $settings = get_option('d14k_feed_settings', array());
            $channels = isset($settings['yml_channels']) ? $settings['yml_channels'] : array();
            if (!empty($channels['prom'])) {
                $ok = $this->yml_generator->generate('prom');
                if (!$ok) {
                    return array('success' => false, 'message' => 'Не вдалось згенерувати YML-фід для Prom', 'import_id' => null);
                }
            }
        }

        // 2. Build feed URL
        $feed_url = $this->get_prom_feed_url();
        if (!$feed_url) {
            return array('success' => false, 'message' => 'Не вдалось визначити URL фіду Prom.ua', 'import_id' => null);
        }

        // 3. Trigger import on Prom
        $result = $this->api->import_from_url($feed_url);
        if ($result === false) {
            return array('success' => false, 'message' => 'Помилка API: ' . $this->api->last_error, 'import_id' => null);
        }

        $import_id = isset($result['import_id']) ? (int) $result['import_id'] : null;

        update_option('d14k_prom_last_export', array(
            'time'      => current_time('mysql'),
            'feed_url'  => $feed_url,
            'import_id' => $import_id,
            'status'    => 'pending',
        ));

        $msg = $import_id
            ? "Імпорт запущено на Prom.ua. ID завдання: {$import_id}"
            : "Запит на імпорт відправлено (без ID завдання)";

        return array('success' => true, 'message' => $msg, 'import_id' => $import_id);
    }

    /**
     * Check the status of the last batch import on Prom.ua.
     *
     * @return array|false   Status object or false
     */
    public function check_last_import_status()
    {
        $last = get_option('d14k_prom_last_export', array());
        if (empty($last['import_id'])) {
            return false;
        }

        $result = $this->api->get_import_status((int) $last['import_id']);
        if ($result !== false) {
            $last['status'] = isset($result['status']) ? $result['status'] : 'unknown';
            update_option('d14k_prom_last_export', $last);
        }

        return $result;
    }

    // -------------------------------------------------------------------------
    // Strategy 2: Real-time single product sync
    // -------------------------------------------------------------------------

    /**
     * Called by WooCommerce hook when a product is saved in the admin.
     * Only syncs if the product was previously imported from Prom.
     *
     * @param int $product_id  WooCommerce post ID
     */
    public function on_product_save($product_id)
    {
        $settings = get_option('d14k_feed_settings', array());
        if (empty($settings['prom_realtime_sync'])) {
            return; // Feature not enabled
        }

        if (!$this->api->has_token()) {
            return;
        }

        $prom_id = get_post_meta($product_id, D14K_Prom_Importer::META_PROM_ID, true);
        if (!$prom_id) {
            return; // Not a Prom product
        }

        $this->sync_single_product($product_id);
    }

    /**
     * Sync a single WooCommerce product to Prom.ua.
     * Updates: price, stock status, active/inactive.
     *
     * @param int $woo_id  WooCommerce product post ID
     * @return array  ['success' => bool, 'message' => string]
     */
    public function sync_single_product($woo_id)
    {
        if (!$this->api->has_token()) {
            return array('success' => false, 'message' => 'API-токен не налаштований');
        }

        $product = wc_get_product($woo_id);
        if (!$product) {
            return array('success' => false, 'message' => "Товар #{$woo_id} не знайдено у WooCommerce");
        }

        $prom_id    = get_post_meta($woo_id, D14K_Prom_Importer::META_PROM_ID, true);
        $price      = (float) $product->get_regular_price();
        $stock_qty  = $product->get_stock_quantity();
        $stock_stat = $product->get_stock_status();
        $woo_status = $product->get_status();

        // Map WooCommerce stock to Prom presence
        $presence_map = array(
            'instock'    => 'available',
            'outofstock' => 'not_available',
            'onbackorder' => 'order',
        );
        $presence = isset($presence_map[$stock_stat]) ? $presence_map[$stock_stat] : 'available';

        // Map WooCommerce status to Prom status
        $prom_status = ($woo_status === 'publish') ? 'on_display' : 'not_on_display';

        $fields = array(
            'price'    => $price,
            'presence' => $presence,
            'status'   => $prom_status,
        );

        if ($stock_qty !== null) {
            $fields['quantity_in_stock'] = (int) $stock_qty;
        }

        // Use external_id sync if prom_id not known
        if ($prom_id) {
            $result = $this->api->edit_product((int) $prom_id, $fields);
        } else {
            $result = $this->api->edit_product_by_external_id((string) $woo_id, $fields);
        }

        if ($result === false) {
            return array('success' => false, 'message' => 'Помилка API: ' . $this->api->last_error);
        }

        return array('success' => true, 'message' => "Товар #{$woo_id} синхронізовано з Prom.ua");
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    /**
     * Return the public URL of the Prom YML feed endpoint.
     * Pattern: {site_url}/marketplace-feed/prom/
     *
     * @return string|false
     */
    private function get_prom_feed_url()
    {
        $settings = get_option('d14k_feed_settings', array());

        // Allow manual override in settings
        if (!empty($settings['prom_feed_url_override'])) {
            return esc_url_raw($settings['prom_feed_url_override']);
        }

        $home = home_url('/');
        return rtrim($home, '/') . '/marketplace-feed/prom/';
    }
}
